samples: ../conf/samples.tsv
units: ../conf/units.tsv
ped: ../conf/samples.ped
internal_sid: "LIMS"

references:
    basepath: "/mnt/references"
    provider: "gatk"
    release: "hg38"

genome_fasta: "Homo_sapiens_assembly38.fasta"

known_variants:
    dbsnp: "Homo_sapiens_assembly38.dbsnp138.vcf"
    hapmap: "hapmap_3.3.hg38.vcf.gz"
    g1k: "1000G_phase1.snps.high_confidence.hg38.vcf.gz"
    omni: "1000G_omni2.5.hg38.vcf.gz"
    mills: "Mills_and_1000G_gold_standard.indels.hg38.vcf.gz"
    #ph1_indels: "known_variants/1000G_phase1.indels.hg19.sites.vcf"
    ph1_indels: "Homo_sapiens_assembly38.known_indels.vcf.gz"


intervals:
    AgilentSureSelectHumanAllExonV6r2:
        bedTarget: "intervals/RefSeq_All_ncbiHg38_merged.bed"
        hsProbes: "intervals/AgilentSureSelectHumanAllExonV6r2_S07604514_Covered.hg38.HybridSelection"
        hsTarget: "intervals/AgilentSureSelectHumanAllExonV6r2_S07604514_Regions.hg38.HybridSelection"

    AgilentSureSelectHumanAllExonV7:
        bedTarget: "intervals/AgilentSureSelectHumanAllExonV7_S31285117_Regions.hg38.bed"
        hsProbes: "intervals/AgilentSureSelectHumanAllExonV7_S31285117_MergedProbes.hg38.HybridSelection"
        hsTarget: "intervals/AgilentSureSelectHumanAllExonV7_S31285117_Regions.hg38.HybridSelection"

    IDT_xGen_ExomeResearchPanel_v1:
        bedTarget: "intervals/xgen-exome-research-panel-v1-targets-hg38.bed"
        hsProbes: "intervals/xgen-exome-research-panel-v1-probes-hg38.HybridSelection"
        hsTarget: "intervals/xgen-exome-research-panel-v1-targets-hg38.HybridSelection"

    IDT_xGen_ExomeResearchPanel_v2:
        bedTarget: "intervals/xgen-exome-research-panel-v2-targets-hg38.bed"
        hsProbes: "intervals/xgen-exome-research-panel-v2-probes-hg38.HybridSelection"
        hsTarget: "intervals/xgen-exome-research-panel-v2-targets-hg38.HybridSelection"

    ccds:
        bedTarget: "intervals/ccds_hg38_Target.bed"
        hsProbes: "intervals/ccds_hg38_Probes.HybridSelection"
        hsTarget: "intervals/ccds_hg38_Target.HybridSelection"


intervals_default: "IDT_xGen_ExomeResearchPanel_v2"
samples_intervals:
    DNA16-0389-R0001: "_enrichment_kit_"
intervals_ccds: "ccds"
interval_target_list: "BED FILE WITH TARGET POSITIONS FOR COVERAGE CHECK"
tmp_dir: "/mnt/tmp"

rules:
    bwa-mem:
        arguments: "-M"
        platform: "illumina"
    multiqc:
        arguments: "--force --cl_config 'picard_config: { general_stats_target_coverage: [10,20,30] }' --interactive --cl_config 'max_table_rows: 700'"
    trim_galore_pe:
        arguments: "-q 20 --cores 4 --fastqc --fastqc_args '--outdir qc/fastqc --quiet' --paired"
    trim_galore_se:
        arguments: "-q 20 --cores 4 --fastqc --fastqc_args '--outdir qc/fastqc --quiet'"
    picard_MarkDuplicates:
        arguments: "REMOVE_DUPLICATES=false ASSUME_SORTED=true CREATE_INDEX=true"
    picard_WGSMetrics:
        arguments: "MINIMUM_MAPPING_QUALITY=-1 MINIMUM_BASE_QUALITY=-1 READ_LENGTH=150 COUNT_UNPAIRED=true"
    picard_gc:
        params: ""
    gatk_BQSR:
        known_sites:
            - dbsnp
            - mills
            - ph1_indel
    gatk_GenomicsDBImport:
        db_suffix: "db_gatk"
    bedtools_coverage:
        params: ''
